project:
  type: website
  resources: assets/images/
  render:
    - "*.qmd"


website:
  title: "Conștientizarea IA"
  description: "Un ghid pentru utilizarea conștientă a IA la locul de muncă"
  navbar:
    background: "#1696D2"
    collapse: true
    pinned: true
    left:
      - text: Despre Curs
        href: index.qmd
      - text: "Micro-Module"
        menu:
          - text: "Ziua 1: Identificarea funcțiilor bazate pe IA"
            href: modules/module1.qmd
          - text: "Ziua 2: Personalizarea & Bule de Filtrare"
            href: modules/module2.qmd
          - text: "Ziua 3: Gestionarea datelor personale"
            href: 3_day.qmd
          - text: "Ziua 4: Luarea deciziilor folosind IA"
            href: 4_day.qmd
          - text: "Ziua 5: Automatizarea și productivitatea"
            href: 5_day.qmd

format:
  html:
    theme: 
      - cosmo
      - styles/_module.scss
    toc: true


    










